Random data gen
sine-fdn/ileap-extension pull request #100
Opened 2024-08-27 15:52 UTC by raimundo-henriques

2024-09-09 10:49 UTC, zeitgeist requested changes
See comments. 

Let's jump on a call to go through my comments together, please.

2024-09-09 10:49 UTC, zeitgeist commented on gen/src/lib.rs
> +            if tce.hoc_id.is_some() {
we could flip the logic here that we use arbitrary to generate a list of HOCs and TOCs accordingly, and then use this list to derive the shipment footprint (rather than the other way around). 

This would increase readability here, but also would allow us to (potentially) have HOC+TOC generation be used in more than this context. 
Let's discuss during pair programming, please.

2024-09-09 14:08 UTC, raimundo-henriques commented on gen/src/arbitrary_impls.rs
> +impl LowerAToZNumDash {
Credit where it's due: it was @fkettelhoit's! :)

2024-09-09 14:12 UTC, raimundo-henriques commented on gen/src/lib.rs
> +            if tce.hoc_id.is_some() {
That makes a lot of sense! In fact, I wasn't so sure about the overall logical architecture. My question, then, will be how to generate ShipmentFootprints, but I guess we can then selectively put TCEs together.

2024-09-09 14:17 UTC, raimundo-henriques commented on gen/src/lib.rs
> +pub fn gen_rnd_demo_data() -> Result<Vec<ProductFootprint>, Box<dyn Error>> {
I'll need to double check, but that's a good point!

2024-09-09 14:17 UTC, raimundo-henriques commented on gen/src/arbitrary_impls.rs
> +                (inbound, Some(TransportMode::arbitrary(g)))
I'm not sure I understand your question, but here's my reasoning:
- For HOCs with HubType Transshipment, inbound and outbound need to be different;
- I thought that, for that case, a good solution would be to generate the inbound arbitrarily and then, recursively, generate a different outbound

2024-09-09 14:17 UTC, raimundo-henriques commented on gen/src/arbitrary_impls.rs
> +impl Arbitrary for PackagingOrTrEqType {
I don't think so... At least as far as I can tell, all non-native types must be implemented manually (and the only macro supported by quickcheck is [this one](https://docs.rs/quickcheck/latest/quickcheck/macro.quickcheck.html))

2024-09-10 14:00 UTC, raimundo-henriques commented on gen/src/arbitrary_impls.rs
> +    fn shrink(&self) -> Box<dyn Iterator<Item = Self>> {
Here I'm not sure what changes you mean :/

2024-09-10 14:00 UTC, raimundo-henriques commented on gen/src/arbitrary_impls.rs
> +    fn arbitrary(g: &mut quickcheck::Gen) -> Self {
I had to made some adaptations, but there's a commit with these changes! Thanks!

2024-09-10 14:03 UTC, raimundo-henriques commented on gen/src/lib.rs
> +            reference_period_start: Utc::now(),
I've added a `TODO` comment. Thanks!

2024-09-10 14:04 UTC, raimundo-henriques commented on gen/src/lib.rs
> +pub fn gen_rnd_demo_data() -> Result<Vec<ProductFootprint>, Box<dyn Error>> {
You're absolutely right: there was no reason for it to be a `Result`. Thanks!

2024-09-10 14:05 UTC, raimundo-henriques commented on gen/src/lib.rs
> +        loop {
I will add a `TODO` comment to signal it! Thanks!

2024-09-10 15:46 UTC, raimundo-henriques commented on gen/src/lib.rs
> +                panic!("Either Toc or Hoc, but not both, must be provided");
Done! Thanks!

2024-09-10 15:46 UTC, raimundo-henriques commented on gen/src/lib.rs
> +            if tce.hoc_id.is_some() {
I added a `TODO` comment. Thanks

2024-09-17 18:32 UTC, zeitgeist approved these changes

2024-09-17 18:33 UTC, zeitgeist approved these changes

2024-09-17 18:34 UTC, merged