feat: add Action TransportActivityData
sine-fdn/ileap-extension pull request #21
Opened 2024-03-04 12:40 UTC by raimundo-henriques

2024-03-05 10:41 UTC, zeitgeist requested changes
Hello Raimundo, thank you. Looks good except for some minor editing work.

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +Filtering CAN be requested by a [=data recipient=] by setting a conforming [=Filter=] request parameter.
Filtering enables a [=data recipient=] to retrieve a subset of [=Transport Activity Data=]. Filtering is an OPTIONAL capability of a [=host system=] which a data recipent can trigger by setting a [=Filter=] request parameter.

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +Support for [=Filter|filtering=] by a [=host system=] is OPTIONAL such that
I'll push a proposal how to formulate this through a separate branch, @raimundo-henriques

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +        - `HttpStatusCode` 202 indicates the returned data is an incomplete result of the given query. The host system MAY return this `HttpStatusCode` if it principally decides that it's able to obt
let's remove this status code completely, please

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +    If the host system does not return the transport activity data, it MUST return an error HTTP Status Code (4xx, 5xx).
Do we need this additional definition here?

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +    The list MUST be encoded as a JSON array. If the list is empty, the host system MUST return an empty JSON array.
Let's remove this sentence, please

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +    If the request parameter `Filter` is defined, the specified expression SHOULD be evaluated for each Transport Activity Data in the collection, and only [=Transport Activity Data=] where the expre
This specification / explanation here should be part of the filtering section above.

2024-03-05 10:41 UTC, zeitgeist commented on specs/index.bs
> +    If the request parameter `Filter` is defined, the specified expression SHOULD be evaluated for each Transport Activity Data in the collection, and only [=Transport Activity Data=] where the expre
or omitted outright :)

2024-03-11 15:48 UTC, raimundo-henriques commented on specs/index.bs
> +        - `HttpStatusCode` 202 indicates the returned data is an incomplete result of the given query. The host system MAY return this `HttpStatusCode` if it principally decides that it's able to obt
I wasn't entirely sure as to whether you meant the status code 202 or the whole definition, so I decided to go with the former

2024-03-11 15:59 UTC, raimundo-henriques commented on specs/index.bs
> +Filtering CAN be requested by a [=data recipient=] by setting a conforming [=Filter=] request parameter.
I took this to have been replaced by your PR

2024-04-02 20:28 UTC, zeitgeist approved these changes
LGTM. We might need to update the response documentation on authentication token handling

2024-04-02 20:28 UTC, merged