feat: add introduction to data model chapter (with diagram)
sine-fdn/ileap-extension pull request #46
Opened 2024-05-14 16:12 UTC by raimundo-henriques

2024-05-21 17:18 UTC, raimundo-henriques commented
Thank you @GabrielaRubioDomingo ! Updated accordingly

2024-05-22 09:08 UTC, raimundo-henriques commented
You're right, @GabrielaRubioDomingo! Thank you!
I've removed it now

2024-05-22 09:08 UTC, GabrielaRubioDomingo approved these changes

2024-05-22 09:12 UTC, raimundo-henriques commented
Thanks for the approval, @GabrielaRubioDomingo . I've added a changelog entry and removed the 'Consultation Draft' tag. @zeitgeist , can you please double-check if the version number is correct?
Thanks!

2024-05-23 13:34 UTC, zeitgeist requested changes
Looks good to me modulo the comments.

2024-05-23 13:34 UTC, zeitgeist commented on specs/index.bs
> +The relations between these data types are summarized by the diagram below:
I think this sentence is stray / no longer needed. WDYT @raimundo-henriques ?

2024-05-23 13:34 UTC, zeitgeist commented on specs/index.bs
> +Note: A <{TCE}> MUST use either a <{TOC}> or an <{HOC}> (see [[#dt-tce]]). The dashed line aims at
This paragraph also appears as redundant to me.

2024-05-23 13:37 UTC, raimundo-henriques commented on specs/index.bs
> +The relations between these data types are summarized by the diagram below:
Absolutely. Thank you!

2024-05-23 14:16 UTC, raimundo-henriques commented on specs/index.bs
> +Note: A <{TCE}> MUST use either a <{TOC}> or an <{HOC}> (see [[#dt-tce]]). The dashed line aims at
Absolutely! Thanks!

2024-05-24 07:17 UTC, zeitgeist approved these changes

2024-05-24 07:20 UTC, merged