feat: happened-before TCE ordering relativ to the ShipmentFootprint
sine-fdn/ileap-extension pull request #81
Opened 2024-06-18 11:19 UTC by zeitgeist

This is a first proposal to add a "happened-before" relationship between TCEs, mitigated through the highlighted TCE property:

<img width="852" alt="Screenshot 2024-06-18 at 13 17 52" src="https://github.com/sine-fdn/ileap-extension/assets/38831/83e5f94b-8861-4b8a-906f-f913db780b6c">

This PR also adds a semantics chapter for this property: 

<img width="854" alt="Screenshot 2024-06-18 at 13 17 43" src="https://github.com/sine-fdn/ileap-extension/assets/38831/be0b26b7-a653-4f2a-b4a3-bcba8ab93a96">

2024-06-19 12:40 UTC, GabrielaRubioDomingo requested changes
I would make order variable optional. - I agree with the rest :)

2024-06-24 10:11 UTC, raimundo-henriques approved these changes
Thank you, @zeitgeist ! I've spotted a typo but other than that, looks good to me!

2024-06-24 10:11 UTC, raimundo-henriques commented on specs/index.bs
> +on the order in which they TCEs occurred during the transport of the shipment.
```suggestion
on the order in which the TCEs occurred during the transport of the shipment.
```

2024-06-25 16:57 UTC, raimundo-henriques commented
Please consider merging PR #82 into this branch before merging on main.

2024-07-08 16:44 UTC, raimundo-henriques approved these changes

2024-07-10 09:01 UTC, merged